version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: semi-app:latest
    environment:
      TZ: Asia/Seoul
      LANG: ko_KR.UTF-8
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      IAMPORT_API_KEY: ${IAMPORT_API_KEY}
      IAMPORT_API_SECRET: ${IAMPORT_API_SECRET}
    expose:
      - "8080"
    networks:
      - appnet

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
